name: chatapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  firebase_core: ^2.24.2
  google_sign_in: 6.2.1
  firebase_auth: 4.16.0
  lottie: 3.0.0
  introduction_screen: 3.1.12
  google_fonts: 6.1.0
  hexcolor: 3.0.1
  gap: 3.0.1
  avatar_glow: 3.0.1
  emoji_picker_flutter: 1.6.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lottie/
    - assets/logo/
  uses-material-design: true

